version: '3'

services:
    es-facil-pg:
        container_name: es-facil-pg
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: esFacil
            POSTGRES_PASSWORD: postgres

        ports:
        - "5432:5432"
        restart: always

    es-facil-web:
        build: .
        volumes:
        - .:/app
        - ~/.m2:/root/.m2
        working_dir: /app
        ports:
        - "8082:8080"
        command: mvn clean spring-boot:run
        depends_on:
        - es-facil-pg